// <auto-generated />
using System;
using Magnum.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magnum.Api.Migrations
{
    [DbContext(typeof(GerichtDbContext))]
    partial class GerichtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magnum.Model.Nahrung.Data.BeigabeData", b =>
                {
                    b.Property<int>("ZutatenId")
                        .HasColumnType("int");

                    b.Property<int>("GerichtId")
                        .HasColumnType("int");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("ZutatenId", "GerichtId");

                    b.ToTable("ZutatenBeigaben");

                    b.HasData(
                        new
                        {
                            ZutatenId = 1,
                            GerichtId = 1,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 2,
                            GerichtId = 2,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 3,
                            GerichtId = 2,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 4,
                            GerichtId = 3,
                            Menge = 5
                        },
                        new
                        {
                            ZutatenId = 5,
                            GerichtId = 3,
                            Menge = 5
                        },
                        new
                        {
                            ZutatenId = 6,
                            GerichtId = 3,
                            Menge = 5
                        },
                        new
                        {
                            ZutatenId = 7,
                            GerichtId = 3,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 8,
                            GerichtId = 3,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 9,
                            GerichtId = 4,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 10,
                            GerichtId = 5,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 3,
                            GerichtId = 6,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 11,
                            GerichtId = 7,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 12,
                            GerichtId = 7,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 13,
                            GerichtId = 7,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 14,
                            GerichtId = 8,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 15,
                            GerichtId = 8,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 16,
                            GerichtId = 9,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 7,
                            GerichtId = 9,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 17,
                            GerichtId = 10,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 15,
                            GerichtId = 11,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 7,
                            GerichtId = 11,
                            Menge = 100
                        },
                        new
                        {
                            ZutatenId = 18,
                            GerichtId = 11,
                            Menge = 100
                        });
                });

            modelBuilder.Entity("Magnum.Model.Nahrung.Data.GerichtData", b =>
                {
                    b.Property<int>("GerichtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GerichtId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GerichtId");

                    b.ToTable("GerichtData");

                    b.HasData(
                        new
                        {
                            GerichtId = 1,
                            Name = "Backofen-Fisch",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 2,
                            Name = "Gebackene Bohnen und Kichererbsennudeln",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 3,
                            Name = "Brot mit körnigem Frischkäse",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 4,
                            Name = "Eine Banane",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 5,
                            Name = "Ein Bueno",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 6,
                            Name = "Gebackene Bohnen in Tomatensoße",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 7,
                            Name = "Suppe mit Tortellini",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 8,
                            Name = "Haferflocken mit Milch",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 9,
                            Name = "Rührei",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 10,
                            Name = "Handvoll Mandeln",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GerichtId = 11,
                            Name = "Kartoffelbrei",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Magnum.Model.Nahrung.Data.ZutatData", b =>
                {
                    b.Property<int>("ZutatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZutatId"));

                    b.Property<double>("Brennwert")
                        .HasColumnType("float");

                    b.Property<double>("Eiweiß")
                        .HasColumnType("float");

                    b.Property<double>("Fett")
                        .HasColumnType("float");

                    b.Property<double>("Kohlenhydrat")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZutatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZutatId");

                    b.ToTable("ZutatData");

                    b.HasData(
                        new
                        {
                            ZutatId = 1,
                            Brennwert = 232.79999999999998,
                            Eiweiß = 15.239999999999998,
                            Fett = 10.319999999999999,
                            Kohlenhydrat = 19.32,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Backofenfisch"
                        },
                        new
                        {
                            ZutatId = 2,
                            Brennwert = 546.0,
                            Eiweiß = 33.0,
                            Fett = 9.0,
                            Kohlenhydrat = 76.5,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Kichererbsennudeln"
                        },
                        new
                        {
                            ZutatId = 3,
                            Brennwert = 170.0,
                            Eiweiß = 10.0,
                            Fett = 1.0,
                            Kohlenhydrat = 28.0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Gebackene Bohnen"
                        },
                        new
                        {
                            ZutatId = 4,
                            Brennwert = 2587.5,
                            Eiweiß = 112.5,
                            Fett = 15.0,
                            Kohlenhydrat = 472.5,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Dinkelvollkornmehl"
                        },
                        new
                        {
                            ZutatId = 5,
                            Brennwert = 883.80000000000007,
                            Eiweiß = 46.800000000000004,
                            Fett = 46.800000000000004,
                            Kohlenhydrat = 63.0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Sonnenblumenkerne"
                        },
                        new
                        {
                            ZutatId = 6,
                            Brennwert = 267.0,
                            Eiweiß = 9.0,
                            Fett = 21.0,
                            Kohlenhydrat = 14.5,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Leinsamen"
                        },
                        new
                        {
                            ZutatId = 7,
                            Brennwert = 35.850000000000001,
                            Eiweiß = 0.045000000000000005,
                            Fett = 4.0499999999999998,
                            Kohlenhydrat = 0.005000000000000001,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Butter"
                        },
                        new
                        {
                            ZutatId = 8,
                            Brennwert = 46.0,
                            Eiweiß = 6.5,
                            Fett = 2.0,
                            Kohlenhydrat = 0.5,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Körniger Frischkäse"
                        },
                        new
                        {
                            ZutatId = 9,
                            Brennwert = 111.59999999999999,
                            Eiweiß = 1.3799999999999999,
                            Fett = 0.23999999999999999,
                            Kohlenhydrat = 27.599999999999998,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Banane"
                        },
                        new
                        {
                            ZutatId = 10,
                            Brennwert = 125.84,
                            Eiweiß = 1.8919999999999999,
                            Fett = 8.2059999999999995,
                            Kohlenhydrat = 10.890000000000001,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Kinder Bueno"
                        },
                        new
                        {
                            ZutatId = 11,
                            Brennwert = 696.0,
                            Eiweiß = 31.5,
                            Fett = 15.0,
                            Kohlenhydrat = 105.0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Gefüllte Tortellini"
                        },
                        new
                        {
                            ZutatId = 12,
                            Brennwert = 44.200000000000003,
                            Eiweiß = 0.0,
                            Fett = 5.0,
                            Kohlenhydrat = 0.0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Öl"
                        },
                        new
                        {
                            ZutatId = 13,
                            Brennwert = 8.2000000000000011,
                            Eiweiß = 1.0,
                            Fett = 0.0,
                            Kohlenhydrat = 0.57999999999999996,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Sojasoße"
                        },
                        new
                        {
                            ZutatId = 14,
                            Brennwert = 339.0,
                            Eiweiß = 12.5,
                            Fett = 6.5,
                            Kohlenhydrat = 55.0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Haferflocken"
                        },
                        new
                        {
                            ZutatId = 15,
                            Brennwert = 115.2,
                            Eiweiß = 5.9399999999999995,
                            Fett = 6.2999999999999998,
                            Kohlenhydrat = 8.6400000000000006,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Milch"
                        },
                        new
                        {
                            ZutatId = 16,
                            Brennwert = 90.0,
                            Eiweiß = 7.5,
                            Fett = 6.5999999999999996,
                            Kohlenhydrat = 0.41999999999999998,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Ei"
                        },
                        new
                        {
                            ZutatId = 17,
                            Brennwert = 611.0,
                            Eiweiß = 24.0,
                            Fett = 53.0,
                            Kohlenhydrat = 5.7000000000000002,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Mandeln"
                        },
                        new
                        {
                            ZutatId = 18,
                            Brennwert = 552.0,
                            Eiweiß = 16.0,
                            Fett = 0.0,
                            Kohlenhydrat = 112.0,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ZutatName = "Kartoffeln"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
